# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98dd180761cd4c18e638266b6c4219bf433cafe65b9d6a07fdccb16ecfc0eaab9a98878e7c2ab49a33cd4a5d25831e44e9620ee1f09520c4dd34ca4228ba9527

test:
  secret_key_base: 6278fbac8537120696afa070e90b348d862630f01779d82f2e7120a8dae5798c6efff60d7befe6dde78a2c1f7cb7aee5a8e47567bea831c9042b7398d2bd8dae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
