# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8cc2969367fdb0fb12f57ae95c161c4b54947c345892739b2fc46fc9d343c085d3288176408e455e74c3971d3e51742ad548c651aa2591289df447315f250c03

test:
  secret_key_base: 65958ceac9e81fee0600252068b2b46aa31b94b0cbb84ef098a36c91dc0931af915ae0e1e1f6fdbc72fc4e05a842144233c75e4c08233f7d556054efa05ca0fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
